### ISSUE TITLE
Separate unit and functional tests

### ISSUE THREAD

**Issue by nicodh** [TYPO3/extension_builder#3]
Most of the unit tests are not real unit tests in the sense that the instantiate multiple classes etc. So they should be moved to the Functional tests. The real unit tests should extend \TYPO3\CMS\Core\Tests\FunctionalTestCase...

**Comment by helhum** [comment]
> The real unit tests should extend \TYPO3\CMS\Core\Tests\FunctionalTestCase

Unit tests should extend `\TYPO3\CMS\Core\Tests\UnitTestCase`

**Comment by nicodh** [comment]
Oops, of course... That's what I want to change with this issue...

**Comment by nicodh** [comment]
But I wonder if it would make sense to have a Testing context enabled in Unit Tests which configures the extbase_object not to use the Typo3DatabaseBackend as backend...

**Comment by helhum** [comment]
Question is: what do you need the object manager for in unit test?

**Comment by nicodh** [comment]
Ok, you mean if I instantiate all classes directly and inject dependencies explicit I can avoid the class cache...
I will try that.

**Comment by helhum** [comment]
> Ok, you mean if I instantiate all classes directly and inject dependencies explicit I can avoid the class cache...

yes.

But it was an honest question. There might be an edge case, where having the object manager might make sense in a unit test.

But I'd say it is better if you can work around using it

**Comment by nicodh** [comment]
Well I just used the object manager since I always use it to instantiate classes. It 's no a necessary part of the test - just a convenience...
