### ISSUE TITLE
BuilderModuleController maybe not loaded or no autoloader

### ISSUE THREAD

**Issue by cietho** [TYPO3/extension_builder#5]
**Can't login to typo3.org - so I hope you see the issue here on GitHub.**

I get the following error under TYPO3 7.6.1 with PHP-7.0-FPM and Debian 8 (Jessie), when I open the backend module:

```
#1289386765: Could not analyse class: "EBT\ExtensionBuilder\Controller\BuilderModuleController" maybe not loaded or no autoloader?

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1289386765: Could not analyse class: "EBT\ExtensionBuilder\Controller\BuilderModuleController" maybe not loaded or no autoloader? | TYPO3\CMS\Extbase\Object\Container\Exception\UnknownObjectException thrown in file /var/www/bin/typo3_src-7.6.1/typo3/sysext/extbase/Classes/Object/Container/ClassInfoFactory.php in line 37.
```

I tried all suggested solutions, that you can find here: https://wiki.typo3.org/Exception/CMS/1289386765 and also a fresh TYPO3 instalaltion. Extension builder still doesn't work.

**edit:**
I changed my TYPO3 version back to 7.6.0 and now it works.

**Comment by Eddcapone** [comment]
Changing [SYS][exceptionalErrors] with the install tool to 20480 (Represents: E_RECOVERABLE_ERROR | E_USER_DEPRECATED) fixed it for me.
